### Extract and clean time series data

In [1]:
from utils import fetch_log_returns
training_dataset = fetch_log_returns(start = '1995-01-01', end ='1995-12-31')

[*********************100%***********************]  5 of 5 completed


In [12]:
training_dataset.head()

sp500       dax      ftse    nikkei      ibex
Date                                                                       
1995-01-05 00:00:00+00:00 -0.000803 -0.010397 -0.006345 -0.003457 -0.019565
1995-01-06 00:00:00+00:00  0.000738  0.003280  0.010726 -0.004939  0.000000
1995-01-09 00:00:00+00:00  0.000326 -0.002330 -0.003006 -0.003826 -0.014346
1995-01-10 00:00:00+00:00  0.001843  0.004213  0.001504  0.002903 -0.005274
1995-01-11 00:00:00+00:00 -0.000043 -0.000155 -0.003601  0.002408 -0.010125

### Define the problem instance and model parameters

In [3]:
from model_params import LAMBDA_1, LAMBDA_2, LAMBDA_3, NLAYERS, NSHOTS, NUM_ASSETS, SIGMA_TARGET, TWO_QUBIT_GATES, K, N

### Build the circuit Ansatz (without angle embedding)

In [11]:
from ansatz import build_hardware_efficient_ansatz
print('Hardware efficient circuit ansatz')
print()
print(build_hardware_efficient_ansatz(num_qubits=5, num_layers=3).draw())


Hardware efficient circuit ansatz

q0: ─U2─U2─o───────U1─U2─o───────U1─U2─o───────U1─M─
q1: ─U2─U2─X─o─────U1─U2─X─o─────U1─U2─X─o─────U1─M─
q2: ─U2─U2───X─o───U1─U2───X─o───U1─U2───X─o───U1─M─
q3: ─U2─U2─────X─o─U1─U2─────X─o─U1─U2─────X─o─U1─M─
q4: ─U2─U2───────X─U1─U2───────X─U1─U2───────X─U1─M─


### Build the Portfolio Optimization Hamiltonian and run an optimization process


In [7]:
import numpy as np
from qibo.optimizers import optimize
from cost_function import compute_total_energy

# Optimize starting from a random guess for the variational parameters
initial_params = np.random.uniform(0, 2*np.pi, 2*N*NLAYERS + N)

# perform optimization
best, params, extra = optimize(compute_total_energy, initial_params, args=(training_dataset))

# set final solution to circuit instance
print('Ground state energy:', best)
print()
print('Optimal parameters', params)
print()
print('Optimization process info', extra)

Ground state energy: 0.050492103202664666

Optimal parameters [3.35346471 1.11682111 3.83907457 2.77883752 1.18347311 5.29196025
 3.54983532 2.57776112 1.67310385 0.15378182 2.72149751 2.44615354
 2.6122525  2.05782    4.1438673  3.59422264 1.33898858 3.15066558
 2.4454425  2.99641062 4.72586394 2.22334737 5.47324903 5.31138313
 0.57541749]

Optimization process info  message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 0.050492103202664666
       x: [ 3.353e+00  1.117e+00 ...  5.311e+00  5.754e-01]
     nit: 1
   direc: [[ 1.000e+00  0.000e+00 ...  0.000e+00  0.000e+00]
           [ 0.000e+00  1.000e+00 ...  0.000e+00  0.000e+00]
           ...
           [ 0.000e+00  0.000e+00 ...  1.000e+00  0.000e+00]
           [ 0.000e+00  0.000e+00 ...  0.000e+00  1.000e+00]]
    nfev: 76
